#ifndef __GBL_HH__
#define __GBL_HH__

#define GBL_CORE_NAME ${CORE_NAME}
#define GBL_CORE_VERSION_MAJOR ${CORE_VERSION_MAJOR}
#define GBL_CORE_VERSION_MINOR ${CORE_VERSION_MINOR}
#define GBL_CORE_VERSION_PATCH ${CORE_VERSION_PATCH}

#define GBL_PROJECT_NAME ${PROJECT_NAME}
#define GBL_PROJECT_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}
#define GBL_PROJECT_VERSION_MINOR ${PROJECT_VERSION_MINOR}
#define GBL_PROJECT_VERSION_PATCH ${PROJECT_VERSION_PATCH}

#define GBL_STR(s) #s

#ifndef NDEBUG
#define GBL_DEBUG 1
#else
#define GBL_DEBUG 0
#endif

#endif